---
###############################################################################
# Nombre: 01-lab_servidor-principal-03.yaml
# Descripción: Playbook para la instalación de Apache necesario para la
#              creación de las máquinas virtuales.
#
# Autor: Jorge A. Díaz Lara - jorge@integraci.com / jorge.diaz@gmail.com
# Licencia: GPL Versión 3
###############################################################################
- name: Preparación de servidor principal para creación de máquinas virtuales
  hosts: servidor-principal

  tasks:
    - name: Servidor apache en Servidor Principal
      when: ansible_distribution == "CentOS"
      yum: name=httpd state=latest

    - name: Servidor apache en Servidor Principal
      run_once: yes
      when: ansible_distribution == "Fedora"
      dnf: name=httpd state=latest

    - name: Nos aseguramos que esté apache en el servidor
      service: name=httpd state=started
      notify: reinicia apache

    - name: Añadimos el servicio httpd a la configuración del firewall
      firewalld: service=http permanent=true state=enabled
      notify: reinicia firewall

    - name: Instalación del grupo de herramientas de virtualización en CentOS
      when: ansible_distribution == "CentOS"
      command: yum -y groupinstall --with-optional Virtualization warn=no

    - name: Instalación del grupo de herramientas de virtualización en Fedora
      when: ansible_distribution == "Fedora"
      command: dnf -y groupinstall --with-optional Virtualization warn=no

    - name: Activar el servicio de virtualización al arrancar el equipo
      service: name=libvirtd state=started
      notify: reinicia libvirt

  handlers:
    - name: reinicia apache
      service: name=httpd state=restarted enabled=yes

    - name: reinicia firewall
      service: name=firewalld state=restarted enabled=yes

    - name: reinicia libvirt
      service: name=libvirtd state=restarted enable=yes
