- name: Creación de maquinas virtuales - Curso Ayuntamientos
  hosts: servidores-virtuales
  gather_facts: no
  vars:
    dir_archivos_kickstart: /var/www/html 
    dir_scripts_crea_servidores: /home/jdiaz/Documentos/playbooks/scripts-servidores
  
  tasks:   
    - name: Crea archivos kickstart para los servidores virtuales 
      action: template src=templates/kickstart.j2 dest={{dir_archivos_kickstart}}/{{inventory_hostname}}.ks mode="u=rw,g=r,o=r"
      delegate_to: servidor-principal

    - name: Crea directorio para scripts de creación de servidores virtuales
      run_once: yes
      file: dest={{dir_scripts_crea_servidores}} recurse=yes state=directory mode=0755
      delegate_to: servidor-principal

    - name: Crea scripts para instalación de servidores virtuales
      action: template src=templates/crea-servidor.j2 dest={{dir_scripts_crea_servidores}}/{{inventory_hostname}}.sh mode="u=rwx,g=r,o=r"
      delegate_to: servidor-principal

    - name: Crea Servidores Virtuales
      script: "{{dir_scripts_crea_servidores}}/{{inventory_hostname}}.sh"
      delegate_to: servidor-principal
