- name: Creación de archivo /etc/hosts
  hosts: all
  gather_facts: no

  vars:
    dominio: integraci.com.mx
  
  tasks:   
    - name: Crea archivos kickstart para los servidores virtuales 
      shell: echo -ne "\n{{ansible_host}}\t{{inventory_hostname}}.{{dominio}}\t{{inventory_hostname}}\n" >> /etc/hosts
      delegate_to: servidor-principal

